const Mu = () => {
    return (
        <div className="text-center pl-10 pr-10">
            <div className="text-secondary text-header1 font-bold font-georgia">
                Mu Chapter
            </div>
            <div className="text-gray text-paragraph font-georgia text-center">
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab nam nesciunt ipsum, fugiat excepturi laudantium fuga beatae. Quidem accusantium deserunt unde quisquam omnis officiis nisi tenetur. Culpa rem minus excepturi. Quaerat maiores molestias temporibus neque recusandae pariatur soluta aperiam nobis id, ducimus alias magni assumenda voluptatibus earum nihil optio eius dolorum ab consequuntur quo, sunt illo? Nisi nemo hic natus! Sed id expedita animi quidem dicta nulla reiciendis maxime fugiat, voluptatem sit maiores nesciunt aliquid illo neque earum molestiae quasi nobis. Velit facere porro quos quidem? Enim dicta tempora mollitia! Libero itaque quia est, rem quae accusamus eum natus! Ipsa harum error veritatis, perferendis, explicabo eaque vitae commodi nam impedit maxime corporis, autem voluptatibus expedita enim corrupti dicta temporibus nemo?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil suscipit quia ab autem officia, a provident consequatur distinctio tenetur dolores, quos iure perspiciatis placeat quam aut ad commodi inventore nobis. Quis corporis earum dolorem voluptates rerum doloremque consequuntur! Repellendus in, alias vero voluptate quisquam, modi esse mollitia id adipisci blanditiis delectus dignissimos? Ad tempora inventore facilis illum sed! Unde, error! Omnis vel aliquid dolorum eveniet sit blanditiis voluptatum nisi dolore laudantium necessitatibus, hic temporibus cum soluta id iusto perferendis animi fugit? Esse fugiat repellat tenetur eius explicabo exercitationem odio consequuntur! At mollitia aspernatur quisquam id quae eum quasi voluptas error recusandae doloribus nisi tempore, impedit rerum ex minima quis doloremque placeat corporis voluptatem reprehenderit incidunt vero? Doloremque mollitia blanditiis facilis?</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Veritatis corporis modi molestiae. Veniam error, commodi, culpa dolorum pariatur accusamus quis quisquam nostrum fuga alias aperiam eveniet illo iure voluptate nemo. Accusamus repellat, omnis dolores provident voluptatibus dolor enim? Rerum eligendi dolores, debitis commodi, vero placeat autem, explicabo vel tenetur incidunt minus similique illo nostrum fugit! Natus perferendis nesciunt nulla saepe. Molestias, harum veritatis doloremque est explicabo iste cum. Ipsa tempore id, quaerat possimus esse pariatur, illum officiis obcaecati deserunt dicta amet vitae dolore iste unde inventore quo eaque et commodi! Id exercitationem sint ullam esse quas praesentium harum sunt nihil delectus consequatur atque adipisci fugiat nesciunt fugit, voluptatibus quidem repellendus? Optio in atque perspiciatis itaque reprehenderit quo iste, fuga iusto.</p>
            </div>
        </div>
    )
}

export default Mu;