"use client";

import { useEffect, useRef, useState } from "react";

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function formatDate(value) {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Chicago",
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(value));
}

function formatDateTime(value) {
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Chicago",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(new Date(value));
}

function parseQrPayload(rawValue) {
  const raw = rawValue.trim();
  if (UUID_PATTERN.test(raw)) return { eventId: raw, passcode: "" };

  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed.eventId === "string") {
      return {
        eventId: parsed.eventId.trim(),
        passcode: typeof parsed.passcode === "string" ? parsed.passcode.trim() : "",
        qrToken: typeof parsed.qrToken === "string" ? parsed.qrToken.trim() : "",
      };
    }
  } catch {
    // QR values may instead be a URL generated by an event display.
  }

  try {
    const url = new URL(raw);
    return {
      eventId: (url.searchParams.get("eventId") || "").trim(),
      passcode: (url.searchParams.get("passcode") || "").trim(),
      qrToken: (url.searchParams.get("qrToken") || "").trim(),
    };
  } catch {
    return null;
  }
}

function PasscodeInput({ value, onChange, disabled }) {
  const inputs = useRef([]);
  const digits = Array.from({ length: 6 }, (_, index) => value[index] || "");

  const update = (nextDigits) => onChange(nextDigits.join("").replace(/\D/g, "").slice(0, 6));

  const handleChange = (index, nextValue) => {
    const digit = nextValue.replace(/\D/g, "").slice(-1);
    const nextDigits = [...digits];
    nextDigits[index] = digit;
    update(nextDigits);
    if (digit && index < 5) inputs.current[index + 1]?.focus();
  };

  const handlePaste = (event) => {
    event.preventDefault();
    const pasted = event.clipboardData.getData("text").replace(/\D/g, "").slice(0, 6);
    if (!pasted) return;
    onChange(pasted);
    inputs.current[Math.min(pasted.length, 6) - 1]?.focus();
  };

  return (
    <div className="flex gap-2" onPaste={handlePaste} aria-label="Six-digit check-in passcode">
      {digits.map((digit, index) => (
        <input
          key={index}
          ref={(element) => {
            inputs.current[index] = element;
          }}
          aria-label={`Passcode digit ${index + 1}`}
          type="text"
          inputMode="numeric"
          autoComplete={index === 0 ? "one-time-code" : "off"}
          maxLength={1}
          value={digit}
          disabled={disabled}
          onChange={(event) => handleChange(index, event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Backspace" && !digits[index] && index > 0) {
              inputs.current[index - 1]?.focus();
            }
          }}
          className="h-12 w-10 rounded-lg border border-gray-300 text-center text-lg font-bold text-gray-950 outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20 disabled:bg-gray-100 sm:w-12"
        />
      ))}
    </div>
  );
}

function QrScanner({ onScan, onError, disabled }) {
  const videoRef = useRef(null);
  const streamRef = useRef(null);
  const frameRef = useRef(null);
  const [scanning, setScanning] = useState(false);

  const stopScanner = () => {
    if (frameRef.current) cancelAnimationFrame(frameRef.current);
    frameRef.current = null;
    streamRef.current?.getTracks().forEach((track) => track.stop());
    streamRef.current = null;
    setScanning(false);
  };

  useEffect(() => stopScanner, []);

  const startScanner = async () => {
    if (!navigator.mediaDevices?.getUserMedia || !("BarcodeDetector" in window)) {
      onError("QR scanning is not supported by this browser. Use the passcode instead.");
      return;
    }

    try {
      const detector = new window.BarcodeDetector({ formats: ["qr_code"] });
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: { ideal: "environment" } },
        audio: false,
      });
      streamRef.current = stream;
      videoRef.current.srcObject = stream;
      await videoRef.current.play();
      setScanning(true);

      const detect = async () => {
        if (!videoRef.current || !streamRef.current) return;
        try {
          const codes = await detector.detect(videoRef.current);
          if (codes[0]?.rawValue) {
            stopScanner();
            onScan(codes[0].rawValue);
            return;
          }
        } catch {
          // A frame can be unavailable while the camera starts; continue scanning.
        }
        frameRef.current = requestAnimationFrame(detect);
      };
      frameRef.current = requestAnimationFrame(detect);
    } catch {
      stopScanner();
      onError("Camera access was unavailable. Check browser permissions or use the passcode.");
    }
  };

  return (
    <div className="mt-4">
      <video
        ref={videoRef}
        muted
        playsInline
        hidden={!scanning}
        className="mb-3 aspect-video w-full rounded-xl bg-gray-950 object-cover"
        aria-label="Camera preview for QR scanning"
      />
      <button
        type="button"
        onClick={scanning ? stopScanner : startScanner}
        disabled={disabled}
        className="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-800 transition hover:border-primary hover:text-primary disabled:cursor-not-allowed disabled:opacity-60"
      >
        {scanning ? "Stop scanner" : "Scan event QR code"}
      </button>
    </div>
  );
}

export default function AttendancePage() {
  const [events, setEvents] = useState([]);
  const [attendance, setAttendance] = useState([]);
  const [eventId, setEventId] = useState("");
  const [passcode, setPasscode] = useState("");
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [feedback, setFeedback] = useState("");
  const [feedbackType, setFeedbackType] = useState("");

  const loadAttendance = async () => {
    try {
      const response = await fetch("/api/portal/events", { cache: "no-store" });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Unable to load attendance.");
      setEvents(payload.events || []);
      setAttendance(payload.attendance || []);
      const openEvent = (payload.events || []).find((event) => event.is_check_in_open);
      if (openEvent) setEventId((current) => current || openEvent.id);
    } catch (error) {
      setFeedback(error.message || "Unable to load attendance.");
      setFeedbackType("error");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAttendance();
  }, []);

  const submitCheckIn = async (requestedEventId = eventId, requestedPasscode = passcode, qrToken = "") => {
    if (!UUID_PATTERN.test(requestedEventId) || (!/^\d{6}$/.test(requestedPasscode) && qrToken.length < 32)) {
      setFeedback("Select an event and enter its six-digit passcode or scan its QR code.");
      setFeedbackType("error");
      return;
    }
    setSubmitting(true);
    setFeedback("");
    try {
      const response = await fetch("/api/portal/events/check-in", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ eventId: requestedEventId, passcode: requestedPasscode, qrToken }),
      });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error || "Unable to complete check-in.");
      setAttendance((current) => {
        const nextRecord = {
          event_id: payload.attendance.eventId,
          checked_in_at: payload.attendance.checkedInAt,
          status: payload.attendance.status,
        };
        return [
          ...current.filter((record) => record.event_id !== nextRecord.event_id),
          nextRecord,
        ];
      });
      setPasscode("");
      setFeedback(payload.alreadyCheckedIn ? "You are already checked in." : "Check-in complete.");
      setFeedbackType("success");
      await loadAttendance();
      setAttendance((current) => {
        const nextRecord = {
          event_id: payload.attendance.eventId,
          checked_in_at: payload.attendance.checkedInAt,
          status: payload.attendance.status,
        };
        return [
          ...current.filter((record) => record.event_id !== nextRecord.event_id),
          nextRecord,
        ];
      });
    } catch (error) {
      setFeedback(error.message || "Unable to complete check-in.");
      setFeedbackType("error");
    } finally {
      setSubmitting(false);
    }
  };

  const handleScan = (rawValue) => {
    const scan = parseQrPayload(rawValue);
    if (!scan || !UUID_PATTERN.test(scan.eventId)) {
      setFeedback("That QR code is not a valid event check-in code.");
      setFeedbackType("error");
      return;
    }
    if (!events.some((event) => event.id === scan.eventId)) {
      setFeedback("This event is not available for your account.");
      setFeedbackType("error");
      return;
    }
    setEventId(scan.eventId);
    if (scan.qrToken?.length >= 32) {
      setPasscode("");
      submitCheckIn(scan.eventId, "", scan.qrToken);
      return;
    }
    if (/^\d{6}$/.test(scan.passcode)) {
      setPasscode(scan.passcode);
      submitCheckIn(scan.eventId, scan.passcode);
      return;
    }
    setFeedback("Event selected. Enter the six-digit passcode to complete check-in.");
    setFeedbackType("");
  };

  const eventById = new Map(events.map((event) => [event.id, event]));
  const history = [...attendance]
    .map((record) => ({ ...record, event: eventById.get(record.event_id) }))
    .filter((record) => record.event)
    .sort((a, b) => new Date(b.checked_in_at) - new Date(a.checked_in_at));
  const completedEvents = events.filter((event) => new Date(event.end_time) <= new Date());
  const attendedEvents = completedEvents.filter((event) =>
    attendance.some((record) => record.event_id === event.id && ["present", "late"].includes(record.status))
  ).length;
  const attendancePercent = completedEvents.length
    ? Math.round((attendedEvents / completedEvents.length) * 100)
    : 0;

  return (
    <div>
      <p className="text-sm font-semibold uppercase tracking-[0.2em] text-primary">Member portal</p>
      <h1 className="mt-2 text-3xl font-bold text-gray-950">Attendance</h1>
      <p className="mt-3 max-w-3xl text-sm leading-6 text-gray-700">
        Check in to an open event with its passcode or a secure event QR code, then review your attendance record.
      </p>

      {feedback && (
        <p className={`mt-5 rounded-lg border px-4 py-3 text-sm font-medium ${feedbackType === "error" ? "border-red-200 bg-red-50 text-red-800" : "border-green-200 bg-green-50 text-green-800"}`} role={feedbackType === "error" ? "alert" : "status"}>
          {feedback}
        </p>
      )}

      {loading ? <p className="mt-8 text-sm text-gray-600">Loading attendance…</p> : (
        <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,3fr)_minmax(280px,2fr)]">
          <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
            <h2 className="text-xl font-bold text-gray-950">Event check-in</h2>
            <label htmlFor="attendance-event" className="mt-5 block text-sm font-semibold text-gray-800">Open event</label>
            <select id="attendance-event" value={eventId} onChange={(event) => setEventId(event.target.value)} disabled={submitting} className="mt-2 w-full rounded-lg border border-gray-300 px-4 py-3 text-gray-950 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20 disabled:bg-gray-100">
              <option value="">Choose an event</option>
              {events.filter((event) => event.is_check_in_open).map((event) => <option key={event.id} value={event.id}>{event.title} — {formatDateTime(event.start_time)}</option>)}
            </select>
            {events.every((event) => !event.is_check_in_open) && <p className="mt-3 text-sm text-gray-600">There are no open check-ins right now.</p>}
            <p className="mt-6 text-sm font-semibold text-gray-800">Six-digit passcode</p>
            <div className="mt-3"><PasscodeInput value={passcode} onChange={setPasscode} disabled={submitting} /></div>
            <button type="button" onClick={() => submitCheckIn()} disabled={submitting || !eventId} className="mt-5 rounded-lg bg-primary px-5 py-3 text-sm font-semibold text-white transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-60">
              {submitting ? "Checking in…" : "Check in"}
            </button>
            <div className="mt-6 border-t border-gray-100 pt-5">
              <p className="text-sm font-semibold text-gray-800">Use a QR code</p>
              <p className="mt-1 text-xs leading-5 text-gray-600">Camera access is requested only when you start scanning and is stopped immediately after a scan.</p>
              <QrScanner onScan={handleScan} onError={(message) => { setFeedback(message); setFeedbackType("error"); }} disabled={submitting} />
            </div>
          </section>

          <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
            <h2 className="text-xl font-bold text-gray-950">Your attendance history</h2>
            {history.length === 0 ? (
              <p className="mt-5 text-sm text-gray-600">No attendance records yet.</p>
            ) : (
              <div className="mt-5 space-y-3">
                {history.map((record) => (
                  <article key={record.event_id} className="rounded-xl border border-gray-100 bg-gray-50 p-4">
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <h3 className="font-semibold text-gray-950">{record.event.title}</h3>
                        <p className="mt-1 text-sm text-gray-600">Checked in {formatDateTime(record.checked_in_at)}</p>
                      </div>
                      <span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-semibold capitalize ${record.status === "present" ? "bg-green-100 text-green-800" : record.status === "late" ? "bg-amber-100 text-amber-800" : "bg-gray-100 text-gray-700"}`}>
                        {record.status}
                      </span>
                    </div>
                  </article>
                ))}
              </div>
            )}
          </section>
        </div>
      )}
    </div>
  );
}
